documentation_module: documentation_module.c main_module_entry_point.c print_module.c
	gcc -Wall -Werror -Wextra -DQ2 documentation_module.c main_module_entry_point.c print_module.c -o ../build/Quest_2

print_module: documentation_module.c main_module_entry_point.c print_module.c
	gcc -Wall -Werror -Wextra -DQ main_module_entry_point.c print_module.c -o ../build/Quest_1

clean:

rebuild:
