S := ../build

door_struct: 
	gcc -Werror -Wextra -Wall dmanager_module.c -o $S/Quest_1

list_test:
	gcc -Werror -Wextra -Wall  list_test.c list.c  -o $S/Quest_2

stack_test:
	gcc -Werror -Wextra -Wall stack.c stack_test.c  -o $S/Quest_3
